### ISSUE TITLE
Click on component definition from palette causes error for plugins with single file diagrams

### ISSUE THREAD

**Issue by viennem** [ditrit/leto-modelizer#407]
**Describe the bug**

For plugins with single file diagrams (ex: `githubator-plugin`: 1 diagram = 1 workflow = 1 file), when I <ins>click</ins> on a component definition in the components palette, I get the following error:

```
Project.js:927 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map')
    at getModelFiles (Project.js:927:1)
    at async onClickItem (ComponentDefinitionCard.vue:120:1)
```

I also get this warning:

```
[Vue warn]: Unhandled error during execution of native event handler 
  at <QCard id="component-definition-job" flat="" bordered=""  ... > 
  at <ComponentDefinitionCard definition= GenericComponentDefinition {type: 'job', icon: 'DefaultJob', model: 'job', displayName: 'Job', description: 'A workflow run is made up of one or more jobs, which run in parallel by default.', …} plugin-name="githubator-plugin" class="full-height" > 
  at <ComponentDefinitionGrid definitions= (6) [Proxy(GenericComponentDefinition), Proxy(GenericComponentDefinition), Proxy(TriggerDefinition), Proxy(TriggerDefinition), Proxy(ComponentDefinition), Proxy(ComponentDefinition)] plugin-name="githubator-plugin" class="q-mt-xs q-pr-sm" > 
  at <QItem key=0 style= {overflow-y: 'auto !important'} class="q-pa-none q-mb-sm" > 
  at <QList text-white="" class="column no-wrap col-shrink" > 
  at <LibraryList plugin= GithubActionPlugin {configuration: GithubActionConfiguration, data: DefaultData, __drawer: GithubActionDrawer, __metadata: GithubActionMetadata, __parser: GithubActionParser, …} templates= [] > 
  at <ComponentDefinitionsList key=0 plugin= GithubActionPlugin {configuration: GithubActionConfiguration, data: DefaultData, __drawer: GithubActionDrawer, __metadata: GithubActionMetadata, __parser: GithubActionParser, …} templates= []  ... > 
  at <QTabPanel name="components" class="q-pa-none" > 
  at <BaseTransition appear=false persisted=false mode=undefined  ... > 
  at <Transition name=null > 
  at <QTabPanels modelValue="components" onUpdate:modelValue=fn animated=""  ... > 
  at <QSplitter modelValue=15 onUpdate:modelValue=fn limits= (2) [10, 15]  ... > 
  at <QDrawer modelValue=true onUpdate:modelValue=fn no-swipe-close=""  ... > 
  at <ModelizerDrawLeftDrawer key=0 plugin= GithubActionPlugin {configuration: GithubActionConfiguration, data: DefaultData, __drawer: GithubActionDrawer, __metadata: GithubActionMetadata, __parser: GithubActionParser, …} templates= []  ... > 
  at <QLayout view="hHh LpR fFf" > 
  at <ModelizerDrawLayout onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) {__v_skip: true} > > 
  at <RouterView> 
  at <App>
```
</details>

**Note**

* Drag & drop and "dependency wheel" (<kbd>+</kbd> button) work properly for adding components.
* This bug does not happen for plugins with folder diagrams (ex: `terrator-plugin`: 1 diagram = 1 folder).

**To Reproduce**

https://github.com/ditrit/leto-modelizer/assets/20184007/17c7a118-66cb-4309-b73f-b6a1dda54b28

**Application**

- `leto-modelizer` version: `1.3.0`.
- `leto-modelizer-plugin-core` version: `0.21.0`.
- `githubator-plugin` version: `0.2.5`.

**Comment by viennem** [comment]
### Investigation

The case where the model path is a file (not a directory) has not been handled:

https://github.com/ditrit/leto-modelizer/blob/f57e57eb9c6ed983fdc9676b020e365d17153421/src/composables/Project.js#L923-L930

* `readDir` is called, even when the model path is a file.

I can see that this case is handled in other functions, such as this one: https://github.com/ditrit/leto-modelizer/blob/f57e57eb9c6ed983fdc9676b020e365d17153421/src/composables/PluginManager.js#L169-L171

So my guess is that this is just an oversight ("un oubli").
